{{- if eq .Values.cloudProvider "azure" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.azure.files.storageClass | quote }}
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
 - dir_mode=0777
 - file_mode=0777
 - uid=0
 - gid=0
 - mfsymlinks
 - cache=strict
 - actimeo=30
 - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks
parameters:
  skuName: Standard_LRS
  #location: us-east-1
  resourceGroup: {{ .Values.azure.files.resourceGroupName | quote }}
  storageAccount: {{ .Values.azure.files.storageAccountName | quote }}
  #customEndpoint: cselsnbsdelowmainacc-file
  shareName: nbs-datacompareapi
{{- end }}
