{{- if eq .Values.cloudProvider "aws" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.pvc.dcPvClaim.storageClass | quote }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.efsFileSystemId | quote }}
  directoryPerms: "700"
{{- end }}
