replicaCount: 1
env: "test1"
image:
  repository: 501715613725.dkr.ecr.us-east-1.amazonaws.com/cdc-nbs-modernization/deduplication-api
  pullPolicy: IfNotPresent
  tag: 7.11.0-SNAPSHOT.67ff78d
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  annotations: {}
  name: ""
podSecurityContext: {}
podAnnotations: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8083
  httpsPort: 443
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
jdbc:
  nbs:
    dbserver:
    username:
    password:
  deduplication:
    dbserver:
    username:
    password:
  mpi:
    dbserver:
    username:
    password:
deduplication:
  # url for Record Linker API
  recordLinker:
    url:
  algorithm:
    # should data elements and algorithm updates be pushed to Record Linker API
    updateRecordLinker: false
  sync:
    enabled: false
# Override available for readiness and liveness probes: path, initialDelaySeconds, periodSeconds, failureThreshold
probes:
  readiness:
    enabled: true
    path: /nbs/api/deduplication/health
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5
  liveness:
    enabled: true
    path: /nbs/api/deduplication/health
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 5
