# ================================================
# Global configuration
# ================================================

replicaCount: 1
env: prod              # Environment indicator
timezone: UTC          # Container timezone

dburl:
  odse: "jdbc:sqlserver://cdc-nbs-fts1-rds-mssql.cvvnwr59v2sd.us-east-1.rds.amazonaws.com:1433;databaseName=NBS_ODSE;encrypt=true;trustServerCertificate=true;"
  rdb: "jdbc:sqlserver://cdc-nbs-fts1-rds-mssql.cvvnwr59v2sd.us-east-1.rds.amazonaws.com:1433;databaseName=rdb_modern;encrypt=true;trustServerCertificate=true;"

kafka:
  cluster: ""

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/path: /actuator/prometheus
  prometheus.io/port: '8081'

resources:
  limits:
    memory: ''         # User should set
    cpu: ''            # User should set
  requests:
    memory: ''         # User should set
    cpu: ''            # User should set

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

probes:
  readiness:
    enabled: true
  liveness:
    enabled: true

# ================================================
# Service-specific configurations
# ================================================
services:

  # ----------------------------------------
  # Investigation Reporting Service
  # ----------------------------------------
  investigation-reporting:
    jdbc:
      username: ""
      password: ""
    service:
      port: 8093
      httpsPort: 443
    serviceAccount:
      create: true
      name: ''
      annotations: {}
    featureFlag:
      phcDatamartEnable: "true"
    log:
      path: /usr/share/investigation-reporting/data
    probes:
      readiness:
        enabled: true
        path: /reporting/investigation-svc/status
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 5
      liveness:
        enabled: true
        path: /reporting/investigation-svc/status
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 5
    image:
      repository: "quay.io/us-cdcgov/cdc-nbs-modernization/data-reporting-service"
      name: "investigation-reporting-service"
      tag: "v1.1.9"
      pullPolicy: IfNotPresent

  # ----------------------------------------
  # LDF Data Reporting Service
  # ----------------------------------------
  ldfdata-reporting:
    jdbc:
      username: ""
      password: ""
    service:
      port: 8097
      httpsPort: 443
    serviceAccount:
      create: true
      name: ''
      annotations: {}
    log:
      path: /usr/share/ldfdata-reporting/data
    probes:
      readiness:
        enabled: true
        path: /reporting/ldfdata-svc/status
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 5
      liveness:
        enabled: true
        path: /reporting/ldfdata-svc/status
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 5
    image:
      repository: "quay.io/us-cdcgov/cdc-nbs-modernization/data-reporting-service"
      name: "ldfdata-reporting-service"
      tag: "v1.1.9"
      pullPolicy: IfNotPresent


  # ----------------------------------------
  # Observation Reporting Service
  # ----------------------------------------
  observation-reporting:
    jdbc:
      username: ""
      password: ""
    service:
      port: 8094
      httpsPort: 443
    serviceAccount:
      create: true
      name: ''
      annotations: {}
    log:
      path: /usr/share/observation-reporting/data
    probes:
      readiness:
        enabled: true
        path: /reporting/observation-svc/status
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 5
      liveness:
        enabled: true
        path: /reporting/observation-svc/status
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 5
    image:
      repository: "quay.io/us-cdcgov/cdc-nbs-modernization/data-reporting-service"
      name: "observation-reporting-service"
      tag: "v1.1.9"
      pullPolicy: IfNotPresent

  # ----------------------------------------
  # Organization Reporting Service
  # ----------------------------------------
  organization-reporting:
    jdbc:
      username: ""
      password: ""
    service:
      port: 8092
      httpsPort: 443
    serviceAccount:
      create: true
      name: ''
      annotations: {}
    log:
      path: /usr/share/organization-reporting/data
    probes:
      readiness:
        enabled: true
        path: /reporting/organization-svc/status
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 5
      liveness:
        enabled: true
        path: /reporting/organization-svc/status
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 5
    image:
      repository: "quay.io/us-cdcgov/cdc-nbs-modernization/data-reporting-service"
      name: "organization-reporting-service"
      tag: "v1.1.9"
      pullPolicy: IfNotPresent

  # ----------------------------------------
  # Person Reporting Service
  # ----------------------------------------
  person-reporting:
    jdbc:
      username: ""
      password: ""
    service:
      port: 8091
      httpsPort: 443
    serviceAccount:
      create: true
      name: ''
      annotations: {}
    featureFlag:
      elasticSearchEnable: "true"
    log:
      path: /usr/share/person-reporting/data
    probes:
      readiness:
        enabled: true
        path: /reporting/person-svc/status
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 5
      liveness:
        enabled: true
        path: /reporting/person-svc/status
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 5
    image:
      repository: "quay.io/us-cdcgov/cdc-nbs-modernization/data-reporting-service"
      name: "person-reporting-service"
      tag: "v1.1.9"
      pullPolicy: IfNotPresent

  # ----------------------------------------
  # Post-Processing Reporting Service
  # ----------------------------------------
  post-processing-reporting:
    jdbc:
      username: ""
      password: ""
    service:
      port: 8095
      httpsPort: 443
      fixedDelay:
        cachedIds: 2
    serviceAccount:
      create: true
      name: ''
      annotations: {}
    log:
      path: /usr/share/post-processing-reporting/data
    probes:
      readiness:
        enabled: true
        path: /reporting/post-processing-svc/status
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 5
      liveness:
        enabled: true
        path: /reporting/post-processing-svc/status
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 5
    image:
      repository: "quay.io/us-cdcgov/cdc-nbs-modernization/data-reporting-service"
      name: "post-processing-reporting-service"
      tag: "v1.1.9"
      pullPolicy: IfNotPresent
